name: fitness_ai_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2

  # Fonts
  google_fonts: ^6.1.0

  # UI & Charts
  fl_chart: ^0.66.2

  # Camera & Permissions
  camera: ^0.10.6
  permission_handler: ^11.4.0

  # AI & Image Processing
  tflite_flutter_plus: ^0.0.1
  image: ^4.1.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/movenet.tflite

